=== FatSharky/Task4/src/by/training/news/source/NewsShema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.traning.by/NewsShema"
	xmlns:tns="http://www.traning.by/NewsShema" elementFormDefault="qualified">
	<element name="blog">
		<complexType>
			<sequence>
				<element name="CATEGORY" type="tns:Category" minOccurs="1"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>
	<complexType name="Category">
		<sequence>
			<element name="SUBCATEGORY" type="tns:Subcategory" minOccurs="1"
	maxOccurs="unbounded" />
		</sequence>
		<attribute name="name" type="string" use="required" />
	</complexType>
	<complexType name="Subcategory">
		<sequence>
			<element name="NEWS" type="tns:News" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
		<attribute name="name" type="string" use="required"/>
	</complexType>
	<complexType name="News">
	<sequence>
	<element name="NEWS_NAME" type="string"/>
	<element name="PROVIDER" type="string" minOccurs="0"/>
	<element name="AUTHOR" type="string" minOccurs="0"/>
	<element name="AUTHORS" type="string" minOccurs="0"/>
	<element name="DATE_OF_ISSUE" type="date"/>
	<element name="NEWS_BODY" type="string"/>
	</sequence>
	</complexType>

</schema>

=== FatSharky/Task4/src/by/training/news/source/News.xml
<?xml version="1.0" encoding="UTF-8"?>
<blog xmlns="http://www.traning.by/NewsShema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.traning.by/NewsShema NewsShema.xsd">

	<CATEGORY name="Фильмы">
		<SUBCATEGORY name="Новинки кино">
			<NEWS>
				<NEWS_NAME>ВАРКРАФТ</NEWS_NAME>
				<AUTHOR>Дункан Джонс</AUTHOR>
				<DATE_OF_ISSUE>2016-05-26</DATE_OF_ISSUE>
				<NEWS_BODY>Вышел долгожданный филь Варкрафт</NEWS_BODY>
			</NEWS>

			<NEWS>
				<NEWS_NAME>Люди икс:Апокалипсис</NEWS_NAME>
				<AUTHOR>Грэг Капулло</AUTHOR>
				<DATE_OF_ISSUE>2016-05-16</DATE_OF_ISSUE>
				<NEWS_BODY>Вышел один из самых неоднозначных фильмов</NEWS_BODY>
			</NEWS>
		</SUBCATEGORY>

		<SUBCATEGORY name="Ужасы">
			<NEWS>
				<NEWS_NAME>Комната страха 28</NEWS_NAME>
				<AUTHORS>Джош Грэг, Грэг джош</AUTHORS>
				<DATE_OF_ISSUE>2016-04-01</DATE_OF_ISSUE>
				<NEWS_BODY>Имена авторов интереснее чем cам фильм</NEWS_BODY>
			</NEWS>
			<NEWS>
				<NEWS_NAME>Звонок перерожение</NEWS_NAME>
				<AUTHORS>Мартин, Мартин</AUTHORS>
				<DATE_OF_ISSUE>2016-05-16</DATE_OF_ISSUE>
				<NEWS_BODY>Cамый мощный тамдем вернулся чтобы расказать вам новую историю</NEWS_BODY>
			</NEWS>
		</SUBCATEGORY>
	</CATEGORY>

	<CATEGORY name="Диски">
		<SUBCATEGORY name="Рэпчик">
			<NEWS>
				<NEWS_NAME>Я положу в тебя патрон</NEWS_NAME>
				<PROVIDER>Biako Records</PROVIDER>
				<DATE_OF_ISSUE>2016-05-16</DATE_OF_ISSUE>
				<NEWS_BODY>Yo yo yo новый тречидала вышел</NEWS_BODY>
			</NEWS>
		</SUBCATEGORY>
		<SUBCATEGORY name="Класика">
			<NEWS>
				<NEWS_NAME>Новы альбом современного класика</NEWS_NAME>
				<PROVIDER>Филармония</PROVIDER>
				<DATE_OF_ISSUE>2016-05-16</DATE_OF_ISSUE>
				<NEWS_BODY>Новый диск выпустил знаменитый классик</NEWS_BODY>
			</NEWS>
		</SUBCATEGORY>
	</CATEGORY>

</blog>
